coverage:
  precision: 2
  round: down
  range: "50...80"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no

