version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/buzzfeed/sso
    steps:
      - run:
          name: Enable go modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
      - checkout
      - setup_remote_docker
      - run:
          name: get tools
          command: make tools
      - run:
          name: run lint and tests for both services
          command: |
            scripts/test
      - run:
          name: build sso-auth
          command: |
            make dist/sso-auth
      - run:
          name: build sso-proxy
          command: |
            make dist/sso-proxy
      - run:
            name: push sso-dev image
            command: |
              if [[ -n $DOCKER_USER ]]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                make imagepush
              fi
      - codecov/upload:
          file: ./scripts/coverage.out
